"""
charon/gateway/routes/concierge.py
System Version: v3.2.0 | File Revision: 3.2.0

Module: REST gateway endpoints for resident Concierge Service interactions, briefings, evaluations,
presence indicators, multi-modal sensory context perception streams, and Speech/Audio synthesis & transcription.
"""

import base64
import logging
from typing import Any, Dict, List, Optional
from fastapi import APIRouter, File, HTTPException, Request, UploadFile
from pydantic import BaseModel, Field

from charon.concierge.speech import SpeechEngine

logger = logging.getLogger("Charon.Gateway.Routes.Concierge")

router = APIRouter(prefix="/v1/concierge", tags=["Concierge Core, Perception & Speech"])

# Global Speech Engine Instance
speech_engine = SpeechEngine()


# ============================================================================
# Request & Response Schemas
# ============================================================================

class EvaluateTaskRequest(BaseModel):
    user_query: str = Field(..., description="Original user prompt or command")
    completed_action: str = Field(..., description="Action or tool executed by agent ecosystem")
    execution_result: str = Field(..., description="Text result output from action execution")
    blackboard_artifacts: Optional[str] = Field(default="", description="Blackboard state or artifacts string")


class InteractRequest(BaseModel):
    user_input: str = Field(..., description="Natural language interaction query from user")


class WindowContextRequest(BaseModel):
    app_name: str = Field(..., description="Target application name (e.g. 'VSCode', 'Firefox', 'Alacritty')")
    window_title: str = Field(..., description="Active window title")
    active_file_path: Optional[str] = Field(default=None, description="Active focused file path if applicable")
    pid: Optional[int] = Field(default=None, description="Process ID of focused application")


class IDEContextRequest(BaseModel):
    editor: str = Field(default="VSCode", description="IDE or text editor name")
    file_path: str = Field(..., description="Active source code file path")
    language: Optional[str] = Field(default="python", description="Programming language ID")
    selection_or_diff: Optional[str] = Field(default=None, description="Active selection or code diff buffer")
    diagnostics: Optional[List[Dict[str, Any]]] = Field(default=None, description="LSP compilation errors or warnings")


class SnapshotContextRequest(BaseModel):
    ocr_text: Optional[str] = Field(default=None, description="Extracted OCR text buffer from screen snapshot")
    image_b64: Optional[str] = Field(default=None, description="Base64 encoded PNG display thumbnail")
    source_display: Optional[str] = Field(default="primary", description="Display identifier")


class SpeechSynthesizeRequest(BaseModel):
    text: str = Field(..., description="Text string to synthesize into speech audio")
    voice_id: Optional[str] = Field(default="en_US-charon-neural", description="Target voice synthesis model ID")
    speed: Optional[float] = Field(default=1.0, ge=0.5, le=2.0, description="Speech playback speed multiplier")


# ============================================================================
# Channel 1: Briefing & Presence Endpoints
# ============================================================================

@router.get("/briefing")
async def get_briefing(request: Request, user_id: str = "default"):
    """Fetch dynamic briefing greeting generated by daemon's resident Concierge Service."""
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    try:
        greeting = await concierge.generate_greeting(user_id=user_id)
        return {"greeting": greeting}
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error generating briefing: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/presence")
async def get_presence(request: Request):
    """
    Returns real-time internal status of Concierge, avatar visual state hints,
    speech engine capabilities, and active feature flags.
    """
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    abilities = concierge.registry.get("abilities", {})
    clock_cfg = concierge.registry.get("biological_clock", {})

    return {
        "status": "online",
        "state": "observing" if clock_cfg.get("enable_autonomic_scheduler", True) else "idle",
        "model_name": concierge.model_name,
        "active_abilities": abilities,
        "speech_capabilities": {
            "tts_enabled": speech_engine.enabled,
            "stt_enabled": speech_engine.enabled,
            "visemes_supported": True,
            "default_voice": speech_engine.default_voice,
        },
        "avatar_state": {
            "emotion": "attentive",
            "hud_visibility": True,
            "mode": "resident_daemon",
        },
    }


# ============================================================================
# Channel 2: Dialogue & Intelligence Endpoints
# ============================================================================

@router.post("/evaluate")
async def evaluate_task(payload: EvaluateTaskRequest, request: Request):
    """Evaluate completed action and generate next-step proposal if applicable."""
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    try:
        proposal = await concierge.get_next_step(
            user_query=payload.user_query,
            completed_action=payload.completed_action,
            execution_result=payload.execution_result,
            blackboard_artifacts=payload.blackboard_artifacts or "",
        )
        if not proposal:
            return {"has_proposal": False, "proposal": None}

        return {
            "has_proposal": True,
            "proposal": proposal.model_dump() if hasattr(proposal, "model_dump") else proposal.dict(),
        }
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error evaluating task: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/interact")
async def interact(payload: InteractRequest, request: Request):
    """Conversational endpoint for the Concierge."""
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    try:
        response = await concierge.handle_user_message(payload.user_input)
        return {"response": response}
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error during interaction: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


# ============================================================================
# Channel 3: Sensory & Desktop Perception Ingress Endpoints
# ============================================================================

@router.post("/context/window")
async def ingest_window_context(payload: WindowContextRequest, request: Request):
    """Ingests desktop window focus events (GNOME Shell extension / window manager)."""
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    try:
        if hasattr(concierge.sensor, "log_window_context"):
            concierge.sensor.log_window_context(
                app_name=payload.app_name,
                window_title=payload.window_title,
                active_file_path=payload.active_file_path,
                pid=payload.pid,
            )
        return {"status": "success", "ingested": "window_focus", "app": payload.app_name}
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error ingesting window context: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/context/ide")
async def ingest_ide_context(payload: IDEContextRequest, request: Request):
    """Ingests real-time IDE diagnostics, active buffer selections, or code diffs."""
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    try:
        if hasattr(concierge.sensor, "log_ide_context"):
            concierge.sensor.log_ide_context(
                editor=payload.editor,
                file_path=payload.file_path,
                language=payload.language,
                selection_or_diff=payload.selection_or_diff,
                diagnostics=payload.diagnostics,
            )
        return {"status": "success", "ingested": "ide_buffer", "file": payload.file_path}
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error ingesting IDE context: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/context/snapshot")
async def ingest_snapshot_context(payload: SnapshotContextRequest, request: Request):
    """Ingests screen visual snapshots or desktop OCR text streams."""
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    try:
        if hasattr(concierge.sensor, "log_snapshot_context"):
            concierge.sensor.log_snapshot_context(
                ocr_text=payload.ocr_text,
                image_b64=payload.image_b64,
                source_display=payload.source_display,
            )
        return {"status": "success", "ingested": "visual_snapshot"}
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error ingesting snapshot context: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


# ============================================================================
# Channel 4: Speech & Audio Endpoints (Phase 3)
# ============================================================================

@router.post("/speech/synthesize")
async def synthesize_speech(payload: SpeechSynthesizeRequest):
    """
    Converts text to audio stream (TTS) accompanied by timed viseme mouth-shape cues
    for real-time desktop HUD lip-syncing.
    """
    try:
        result = await speech_engine.synthesize_speech(
            text=payload.text,
            voice_id=payload.voice_id,
            speed=payload.speed or 1.0,
        )
        return result
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error during speech synthesis: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/speech/transcribe")
async def transcribe_speech(
    file: UploadFile = File(...),
    language: Optional[str] = "en"
):
    """
    Ingests raw audio buffers (WAV / OGG / MP3) for local STT transcription.
    """
    try:
        audio_bytes = await file.read()
        result = await speech_engine.transcribe_audio(
            audio_bytes=audio_bytes,
            content_type=file.content_type or "audio/wav",
            language=language or "en",
        )
        return result
    except Exception as exc:
        logger.error(f"[ConciergeRoute] Error during speech transcription: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


# ============================================================================
# Central Registry Control Endpoint
# ============================================================================

@router.post("/registry/reload")
async def reload_registry(request: Request):
    """Reload central JSON registry options into active Concierge Service instance."""
    concierge = getattr(request.app.state, "concierge", None)
    if not concierge:
        raise HTTPException(status_code=503, detail="Concierge Service is not initialized on daemon.")

    concierge.reload_registry()
    return {"status": "ok", "message": "Concierge configuration reloaded from registry."}