"""
charon/core/contracts.py
System Version: v0.2.0 | File Revision: 1.2.1

Module: Core Negotiation Schemas, Diagnostic Flashlight Models, & Role Contracts.
Provides Pydantic V2 schemas for manifest inspection, capability negotiation,
rich diagnostic gap reporting, skill blueprints, and execution output across Charon.
Updated with Pydantic V2 AliasChoices and full two-way property setters for legacy agent fields.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import AliasChoices, BaseModel, ConfigDict, Field


class ExecutionStatus(str, Enum):
    """Status code returned by a role executor following a step negotiation execution."""

    SATISFIED = "SATISFIED"
    PARTIAL = "PARTIAL"
    INCAPABLE = "INCAPABLE"
    FAILED = "FAILED"


class GapType(str, Enum):
    """Taxonomy of capability gaps identified during negotiation or execution (The Flashlight)."""

    ACTION_UNSUPPORTED = "ACTION_UNSUPPORTED"
    MISSING_ARTIFACT = "MISSING_ARTIFACT"
    MISSING_SYSTEM_DEPENDENCY = "MISSING_SYSTEM_DEPENDENCY"
    EXECUTION_ERROR = "EXECUTION_ERROR"


class DiagnosticGap(BaseModel):
    """Structured root-cause diagnostic explaining exactly why a role cannot complete a step."""

    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    gap_type: GapType = Field(
        description="Categorical root-cause identifier for the execution barrier."
    )
    description: str = Field(
        description="Human/LLM readable detail of the missing capability or state."
    )
    missing_key_or_tool: Optional[str] = Field(
        default=None,
        description="Specific missing blackboard artifact key, binary executable, or skill action.",
    )
    suggested_remediation: str = Field(
        description="Actionable guidance for the Coordinator (e.g., fallback role or missing key step)."
    )


class SkillBlueprint(BaseModel):
    """Declarative specification generated by system engineers when ad-hoc solving a recurring task."""

    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    suggested_skill_name: str = Field(
        description="PascalCase name suggested for the new permanent Skill class."
    )
    action_name: str = Field(
        description="Snake_case string identifier for the action capability."
    )
    target_role: str = Field(
        validation_alias=AliasChoices("target_role", "target_agent"),
        description="Target specialist role persona best suited to adopt this skill.",
    )
    description: str = Field(
        description="Summary of what the skill performs and when it should be invoked."
    )
    inputs_required: List[str] = Field(
        default_factory=list,
        description="Blackboard artifact keys required as prerequisites.",
    )
    outputs_produced: List[str] = Field(
        default_factory=list,
        description="Blackboard artifact keys produced upon successful execution.",
    )
    system_dependencies: List[str] = Field(
        default_factory=list,
        description="CLI tools or python packages required by the skill execution.",
    )
    adhoc_code_reference: Optional[str] = Field(
        default=None,
        description="File path or temp log ID where ad-hoc execution code was archived.",
    )

    @property
    def target_agent(self) -> str:
        """Legacy compatibility alias for target_role."""
        return self.target_role

    @target_agent.setter
    def target_agent(self, value: str) -> None:
        self.target_role = value


class ToolManifest(BaseModel):
    """Declarative capability contract exposed by roles during preplanning and discovery."""

    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    role_name: str = Field(
        validation_alias=AliasChoices("role_name", "agent_name"),
        description="Unique string role identity of the specialist.",
    )
    supported_actions: List[str] = Field(
        default_factory=list,
        description="List of capability names or action aliases supported by the role.",
    )
    system_requirements: List[str] = Field(
        default_factory=list,
        description="Required system dependencies or executable binaries (e.g., ['gui', 'xdg-open']).",
    )
    consumed_artifacts: List[str] = Field(
        default_factory=list,
        description="Blackboard artifact keys required as input prerequisites.",
    )
    produced_artifacts: List[str] = Field(
        default_factory=list,
        description="Blackboard artifact keys guaranteed to be produced upon successful execution.",
    )
    description: str = Field(
        description="Human/LLM-readable summary of domain expertise and action scope."
    )

    @property
    def agent_name(self) -> str:
        """Legacy compatibility alias for role_name."""
        return self.role_name

    @agent_name.setter
    def agent_name(self, value: str) -> None:
        self.role_name = value


class CapabilityNegotiation(BaseModel):
    """Coordinator query payload sent to evaluate if a role can fulfill a plan step."""

    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    step_id: str = Field(
        description="Unique step/requirement identifier on the blackboard queue."
    )
    target_action: str = Field(
        description="Capability or action name requested by the Coordinator."
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Bound step parameters and input artifact values.",
    )
    context_keys_available: List[str] = Field(
        default_factory=list,
        description="Artifact keys currently populated on the Shared TaskBlackboard.",
    )


class ContractResponse(BaseModel):
    """Standardized contract response returned by specialist roles back to the Coordinator."""

    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    role_name: str = Field(
        validation_alias=AliasChoices("role_name", "agent_name"),
        description="Identity of the responding specialist role.",
    )
    status: ExecutionStatus = Field(
        description="Outcome status of the negotiation or execution turn."
    )
    accomplishments: List[str] = Field(
        default_factory=list,
        description="Summary of work or sub-tasks completed during execution.",
    )
    blackboard_artifacts_added: List[str] = Field(
        default_factory=list,
        description="Keys newly posted to the Shared TaskBlackboard store.",
    )
    unresolved_gaps: List[str] = Field(
        default_factory=list,
        description="Sub-tasks or missing prerequisites the role could NOT satisfy.",
    )
    diagnostics: Optional[DiagnosticGap] = Field(
        default=None,
        description="Flashlight diagnostic detailing specific root-cause if INCAPABLE or FAILED.",
    )
    skill_blueprint: Optional[SkillBlueprint] = Field(
        default=None,
        description="Optional skill forge blueprint emitted when ad-hoc problem solving occurs.",
    )
    suggested_next_role: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("suggested_next_role", "suggested_next_agent"),
        description="Optional role recommendation if status is INCAPABLE or PARTIAL.",
    )
    reason: Optional[str] = Field(
        default=None,
        description="Detailed diagnostic message or exception string if partial/failed.",
    )

    @property
    def agent_name(self) -> str:
        """Legacy compatibility alias for role_name."""
        return self.role_name

    @agent_name.setter
    def agent_name(self, value: str) -> None:
        self.role_name = value

    @property
    def suggested_next_agent(self) -> Optional[str]:
        """Legacy compatibility alias for suggested_next_role."""
        return self.suggested_next_role

    @suggested_next_agent.setter
    def suggested_next_agent(self, value: Optional[str]) -> None:
        self.suggested_next_role = value